# Generated by Django 2.1.7 on 2019-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190213_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=True, upload_to='worksheets'),
        ),
    ]
