# Generated by Django 2.1.7 on 2019-03-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
